import { AnimatePresence, motion } from 'framer-motion'
import { useEffect, useMemo, useRef, useState } from 'react'

interface Props {
  open: boolean
  onClose: () => void
  title: string
  subtitle?: string
  text: string
  prescription?: string | null
  loading?: boolean
}

// Reveals document text progressively (a subtle "typing" effect), then a caret.
function useTyping(fullText: string, active: boolean, cps = 900) {
  const [shown, setShown] = useState('')
  const raf = useRef<number>()
  useEffect(() => {
    if (!active || !fullText) {
      setShown('')
      return
    }
    setShown('')
    const start = performance.now()
    const tick = (now: number) => {
      const chars = Math.floor(((now - start) / 1000) * cps)
      setShown(fullText.slice(0, chars))
      if (chars < fullText.length) raf.current = requestAnimationFrame(tick)
      else setShown(fullText)
    }
    raf.current = requestAnimationFrame(tick)
    return () => {
      if (raf.current) cancelAnimationFrame(raf.current)
    }
  }, [fullText, active, cps])
  const done = shown.length >= fullText.length
  return { shown, done }
}

export default function DocumentModal({
  open,
  onClose,
  title,
  subtitle,
  text,
  prescription,
  loading,
}: Props) {
  // Note followed by the prescription block (if any), typed as one document.
  const full = useMemo(
    () => (prescription ? `${text}\n\n${'─'.repeat(48)}\n\n${prescription}` : text),
    [text, prescription],
  )
  const { shown, done } = useTyping(full, open && !loading)

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && onClose()
    if (open) window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [open, onClose])

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          <div
            className="absolute inset-0 bg-ink/40 backdrop-blur-sm"
            onClick={onClose}
          />
          <motion.div
            className="relative bg-card border border-line rounded-2xl shadow-card w-full max-w-2xl max-h-[86vh] flex flex-col"
            initial={{ opacity: 0, scale: 0.96, y: 12 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.98, y: 8 }}
            transition={{ type: 'spring', stiffness: 260, damping: 24 }}
          >
            <div className="flex items-start justify-between px-6 py-4 border-b border-line">
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-xs font-semibold uppercase tracking-wide text-rag-amber bg-rag-amber/12 px-2 py-0.5 rounded-full">
                    Draft — for officer review
                  </span>
                </div>
                <h3 className="text-ink font-semibold mt-1.5">{title}</h3>
                {subtitle && (
                  <p className="text-muted text-sm">{subtitle}</p>
                )}
              </div>
              <button
                onClick={onClose}
                className="text-muted hover:text-ink text-xl leading-none px-2"
                aria-label="Close"
              >
                ×
              </button>
            </div>

            <div className="px-6 py-5 overflow-auto">
              {loading ? (
                <div className="flex items-center gap-3 text-muted py-10 justify-center">
                  <span className="inline-block w-4 h-4 border-2 border-brand/30 border-t-brand rounded-full animate-spin" />
                  Generating draft…
                </div>
              ) : (
                <pre className="whitespace-pre-wrap font-sans text-[13.5px] leading-relaxed text-slate-700">
                  {shown}
                  {!done && <span className="caret" />}
                </pre>
              )}
            </div>

            <div className="px-6 py-3 border-t border-line flex items-center justify-between">
              <span className="text-xs text-muted">
                Generated by AROGYA AI · not a final decision
              </span>
              <button
                onClick={onClose}
                className="text-sm font-medium text-white bg-brand hover:bg-ink px-4 py-1.5 rounded-lg transition-colors"
              >
                Close
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}
